name: remote ssh command
on: [push]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.GOORM_HOST }}
                  username: ${{ secrets.GOORM_USERNAME }}
                  password: ${{ secrets.GOORM_PASSWORD }}
                  port: ${{ secrets.GOORM_PORT }}
                  script: /workspace/beomlog.baepo.sh
